# Generated by Django 3.1.5 on 2021-01-23 14:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(default='live')),
                ('live', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listen', models.PositiveIntegerField(default=1935, unique=True, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)])),
            ],
        ),
        migrations.CreateModel(
            name='Push',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True, validators=[django.core.validators.URLValidator(schemes=['rtmp'])])),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nginx_rtmp_wizard.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nginx_rtmp_wizard.server'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('server', 'name'), name='unique_server_application_name'),
        ),
    ]
